title: Axel Van Dyck
logo: /assets/img/cvpic.jpg
description: Â¡Hola! Bienvenido a mi portafolio de Quality Assurance Tester. [Visit my GitHub Profile](https://github.com/avandyck16)
show_downloads: false
theme: jekyll-theme-minimal
